/* KIOSK DATA - siedem symulacji Quantica Lab w jednym schemacie
   Teksty scenariuszy 1:1 z <produkt>_website.html. Wspólny schemat:
   product: { id, name, tagline, tabs[3], nodes{input,process{icons[3]}}, outputs{target:{title,icon,tone}}, viz?, scenarios[] }
   scenario: { input, checks[3], target, preview, rows[[icon,text,cls]], badge, steps[7] } + pola widoku produktowego (route, chips, fields, segments, pairs, scores...) */
window.KIOSK_PRODUCTS = [
  {
    id: "zagloba", name: "Zagłoba", tagline: "inteligentny <em>asystent wiedzy</em> organizacji",
    tabs: ["procedura", "ograniczony dostęp", "brak w bazie"],
    nodes: { input: { title: "Pytanie", icon: "message-square-text" }, process: { title: "Baza wiedzy", icon: "scan-search", icons: ["database", "key-round", "list-ordered"] } },
    outputs: { answer: { title: "Odpowiedź ze źródłami", icon: "file-check" }, nodata: { title: "Brak informacji w bazie", icon: "signpost", tone: "teal" } },
    scenarios: [
      { input: "Jaka jest procedura udostępniania informacji publicznej w naszym urzędzie?",
        checks: ["przeszukiwanie bazy wiedzy organizacji", "kontrola uprawnień: użytkownik ma dostęp do wyszukanych dokumentów", "wyszukiwanie hybrydowe i ponowna ocena trafności wyników"],
        target: "answer",
        preview: "Wniosek można złożyć pisemnie, e-mailem lub przez ePUAP. Odpowiedzi udziela się bez zbędnej zwłoki, nie później niż w terminie 14 dni <span class=\"ref\">[1]</span>. Wniosek rejestruje sekretariat zgodnie z instrukcją obiegu dokumentów <span class=\"ref\">[2]</span>.",
        rows: [["file-text", "[1] Procedura udostępniania informacji publicznej.pdf", ""], ["file-text", "[2] Instrukcja obiegu dokumentów.docx", ""]],
        badge: "informacje można zweryfikować w materiałach źródłowych",
        steps: ["odebrano pytanie użytkownika", "analiza pytania i przygotowanie wyszukiwania", null, null, null, "przygotowanie odpowiedzi na podstawie najbardziej trafnych informacji", "odpowiedź zawiera odwołania do dokumentów źródłowych w formie cytowań"] },
      { input: "Przygotuj podsumowanie ustaleń z dokumentacji projektu wdrożenia",
        checks: ["przeszukiwanie bazy wiedzy: dokumentacja projektu wdrożenia", "kontrola uprawnień: dokumenty bez uprawnień użytkownika pominięte", "ponowna ocena trafności wyników w dostępnych zasobach"],
        target: "answer",
        preview: "Ustalenia: 1) start pilotażu w II kwartale <span class=\"ref\">[1]</span>, 2) odpowiedzialny: zespół wdrożeniowy, kamienie milowe wg harmonogramu <span class=\"ref\">[2]</span>.<span class=\"tr\">Jeden dokument pominięto ze względu na brak uprawnień użytkownika.</span>",
        rows: [["file-text", "[1] Notatka ze spotkania projektowego.docx", ""], ["file-text", "[2] Harmonogram wdrożenia.xlsx", ""], ["lock", "1 dokument pominięty - brak uprawnień użytkownika", "gap"]],
        badge: "odpowiedź na podstawie zasobów dostępnych użytkownikowi",
        steps: ["odebrano pytanie użytkownika", "analiza pytania i przygotowanie wyszukiwania", null, null, null, "odpowiedź generowana wyłącznie na podstawie informacji, do których użytkownik ma uprawnienia", "zachowane istniejące role i poziomy dostępu"] },
      { input: "Jakie zasady rozliczania delegacji zagranicznych będą obowiązywać w przyszłym roku?",
        checks: ["przeszukiwanie bazy wiedzy organizacji", "kontrola uprawnień: zakres wyszukiwania zgodny z dostępem użytkownika", "ocena trafności: brak wystarczających informacji w bazie wiedzy"],
        target: "nodata",
        preview: "W bazie wiedzy nie ma informacji o zasadach rozliczania delegacji zagranicznych na przyszły rok. Obowiązujące dziś zasady opisuje <span class=\"ref\">[1]</span>. Właściwym źródłem informacji o zmianach jest <b>dział finansowy</b>.",
        rows: [["file-text", "[1] Zasady rozliczania delegacji.pdf", ""]],
        badge: "brak danych - wskazano właściwe źródło: dział finansowy",
        steps: ["odebrano pytanie użytkownika", "analiza pytania i przygotowanie wyszukiwania", null, null, null, "system nie tworzy odpowiedzi spekulatywnej", "informacja o braku danych i wskazanie odpowiedniego źródła informacji"] }
    ]
  },
  {
    id: "dyndalski", name: "Dyndalski", tagline: "inteligentny <em>generator dokumentów</em>",
    tabs: ["uchwała", "zawiadomienie", "protokół"],
    nodes: { input: { title: "Wybór gatunku i formularz", icon: "text-cursor-input" }, process: { title: "Generowanie dokumentu", icon: "settings-2", icons: ["list-checks", "layout-template", "spell-check"] } },
    outputs: { doc: { title: "Gotowy dokument", icon: "file-text" } },
    scenarios: [
      { input: "rada przyjmuje regulamin korzystania z parku miejskiego, obowiązuje od 1 września, podstawa prawna do uzupełnienia",
        checks: ["kompletność danych: brak podstawy prawnej - system zaproponował właściwy przepis", "struktura i styl zgodne ze wzorcem gatunkowym", "poprawność językowa i formatowanie"],
        target: "doc",
        preview: "<b>UCHWAŁA NR …/2026 RADY MIASTA …</b> z dnia … r.<br>w sprawie regulaminu korzystania z parku miejskiego<br>Na podstawie art. 40 ust. 2 pkt 4 ustawy z dnia 8 marca 1990 r. o samorządzie gminnym uchwala się, co następuje:<br>§ 1. Ustala się regulamin korzystania z parku miejskiego, stanowiący załącznik do uchwały. <span class=\"more\">(…)</span>",
        rows: [["flag", "podstawa prawna - uzupełniona po podpowiedzi systemu", "gap"], ["file-check", "tytuł, treść (§ 1 - § 4), termin wejścia w życie, podpis", ""]],
        badge: "dokument gotowy do weryfikacji przez pracownika",
        steps: ["wybrano gatunek: uchwała - dane z formularza przekazane do systemu", "analiza danych i dobór wzorca gatunkowego", null, null, null, "wygenerowano kompletny dokument zgodny ze wzorcem gatunkowym", "edycja w przeglądarce i zapis w wybranym formacie"],
        fields: [["gatunek", "uchwała"], ["przedmiot", "regulamin korzystania z parku miejskiego"], ["obowiązuje od", "1 września 2026"], ["podstawa prawna", "", "missing"]],
        suggest: "brakuje podstawy prawnej - proponuję: art. 40 ust. 2 pkt 4 ustawy o samorządzie gminnym; potwierdź lub wpisz własną",
        fill: [3, "art. 40 ust. 2 pkt 4 ustawy o samorządzie gminnym"],
        sections: [["nagłówek", "<b>UCHWAŁA NR …/2026 RADY MIASTA …</b> z dnia … r."], ["przedmiot", "w sprawie regulaminu korzystania z parku miejskiego"], ["podstawa prawna", "Na podstawie art. 40 ust. 2 pkt 4 ustawy z dnia 8 marca 1990 r. o samorządzie gminnym uchwala się, co następuje:"], ["treść", "§ 1. Ustala się regulamin korzystania z parku miejskiego, stanowiący załącznik do uchwały. <span class=\"more\">(…)</span> § 4. Uchwała wchodzi w życie z dniem 1 września 2026 r."], ["podpis", "……………………………"]] },
      { input: "posiedzenie komisji rewizyjnej przesunięte na 12 maja, godz. 14:00, sala 102, poinformować mieszkańców",
        checks: ["kompletność danych: komplet informacji o sprawie", "struktura i styl zgodne ze wzorcem gatunkowym", "poprawność językowa i formatowanie"],
        target: "doc",
        preview: "<b>ZAWIADOMIENIE</b><br>Przewodniczący Komisji Rewizyjnej zawiadamia, że posiedzenie Komisji zostaje przesunięte na <b>12 maja 2026 r., godz. 14:00</b>, sala 102.<br>Posiedzenie ma charakter otwarty. Mieszkańcy mogą uczestniczyć w posiedzeniu bez wcześniejszego zgłoszenia. <span class=\"more\">(…)</span>",
        rows: [["file-check", "oznaczenie organu, data, adresaci", ""], ["file-check", "treść, pouczenie, podpis", ""]],
        badge: "dokument gotowy do weryfikacji przez pracownika",
        steps: ["wybrano gatunek: zawiadomienie - dane z formularza przekazane do systemu", "analiza danych i dobór wzorca gatunkowego", null, null, null, "wygenerowano kompletny dokument zgodny ze wzorcem gatunkowym", "edycja w przeglądarce i zapis w wybranym formacie"],
        fields: [["gatunek", "zawiadomienie"], ["sprawa", "posiedzenie komisji rewizyjnej - zmiana terminu"], ["termin", "12 maja 2026, godz. 14:00"], ["miejsce", "sala 102"], ["adresaci", "mieszkańcy"]],
        sections: [["nagłówek", "<b>ZAWIADOMIENIE</b>"], ["organ", "Przewodniczący Komisji Rewizyjnej"], ["treść", "zawiadamia, że posiedzenie Komisji zostaje przesunięte na <b>12 maja 2026 r., godz. 14:00</b>, sala 102."], ["pouczenie", "Posiedzenie ma charakter otwarty. Mieszkańcy mogą uczestniczyć w posiedzeniu bez wcześniejszego zgłoszenia. <span class=\"more\">(…)</span>"], ["podpis", "……………………………"]] },
      { input: "spotkanie zespołu projektowego 4 czerwca, lista obecności w załączeniu, przyjęto trzy ustalenia, wnioski do realizacji",
        checks: ["kompletność danych: komplet informacji o sprawie", "struktura i styl zgodne ze wzorcem gatunkowym", "poprawność językowa i formatowanie"],
        target: "doc",
        preview: "<b>PROTOKÓŁ</b> ze spotkania zespołu projektowego z dnia 4 czerwca 2026 r.<br>Obecni: zgodnie z listą obecności (załącznik nr 1).<br>Ustalenia: 1) …; 2) …; 3) ….<br>Wnioski do realizacji: <span class=\"more\">(…)</span> - odpowiedzialni i terminy wg tabeli.",
        rows: [["file-check", "nagłówek, data, lista obecności", ""], ["file-check", "przebieg, ustalenia, podpisy", ""]],
        badge: "dokument gotowy do weryfikacji przez pracownika",
        steps: ["wybrano gatunek: protokół - dane z formularza przekazane do systemu", "analiza danych i dobór wzorca gatunkowego", null, null, null, "wygenerowano kompletny dokument zgodny ze wzorcem gatunkowym", "edycja w przeglądarce i zapis w wybranym formacie"],
        fields: [["gatunek", "protokół"], ["spotkanie", "zespół projektowy"], ["data", "4 czerwca 2026"], ["obecni", "wg listy obecności (załącznik)"], ["ustalenia", "3 · wnioski do realizacji"]],
        sections: [["nagłówek", "<b>PROTOKÓŁ</b> ze spotkania zespołu projektowego z dnia 4 czerwca 2026 r."], ["obecni", "zgodnie z listą obecności (załącznik nr 1)"], ["ustalenia", "1) …; 2) …; 3) …."], ["wnioski", "do realizacji: <span class=\"more\">(…)</span> - odpowiedzialni i terminy wg tabeli"], ["podpisy", "……………………………"]] }
    ]
  },
  {
    id: "gerwazy", name: "Gerwazy", tagline: "inteligentna <em>ocena zgodności</em> dokumentacji",
    tabs: ["NIS2", "AI Act", "własna lista kontrolna"],
    nodes: { input: { title: "Dokumentacja i wymagania", icon: "clipboard-list" }, process: { title: "Agenci AI", icon: "users", icons: ["book-open", "search", "flag"] } },
    outputs: { report: { title: "Raport zgodności", icon: "file-check" } },
    scenarios: [
      { input: "Polityka bezpieczeństwa informacji · gotowy zestaw wymagań: NIS2",
        checks: ["interpretacja wymagań NIS2", "analiza dokumentacji organizacji", "identyfikacja luk: wykryto braki w dokumentacji"],
        target: "report",
        preview: "<b>Ocena poziomu zgodności: częściowa</b> · 1 z 3 wymagań<br>01 polityka bezpieczeństwa - spełnione („rozdz. 3: przegląd polityki co 12 miesięcy” · NIS2 art. 21 ust. 2 lit. a)<br>02 obsługa incydentów - niezgodność („rozdz. 7: zgłoszenie w terminie 7 dni” · NIS2 art. 23: wczesne ostrzeżenie w 24 h)<br>03 ciągłość działania - brak w dokumentacji (NIS2 art. 21 ust. 2 lit. c)",
        rows: [["check", "01 polityka bezpieczeństwa - spełnione", ""], ["flag", "02 obsługa incydentów - niezgodność", "gap"], ["flag", "03 ciągłość działania - brak w dokumentacji", "gap"]],
        badge: "rekomendacje: wdrożyć proces zgłaszania incydentów w 24 h, opracować plan ciągłości działania i kopii zapasowych, wprowadzić ocenę ryzyka dostawców IT",
        steps: ["wczytano dokumentację: Polityka bezpieczeństwa informacji", "gotowy zestaw wymagań: NIS2", null, null, null, "raport: 3 wymagania spełnione, 2 niezgodności, 1 brak w dokumentacji", "każda ocena uzasadniona cytowanym fragmentem dokumentu i wskazanym wymaganiem"],
        doc: "Polityka bezpieczeństwa informacji", req: "zestaw wymagań: NIS2", met: 3, total: 6,
        frags: [
          ["„Analizę ryzyka dla systemów informacyjnych przeprowadza się raz w roku.”", "Polityka bezpieczeństwa informacji · rozdz. 2, pkt 2.3", "wynik analizy zatwierdza pełnomocnik ds. bezpieczeństwa"],
          ["„Polityka podlega przeglądowi co 12 miesięcy oraz po każdym istotnym incydencie.”", "Polityka bezpieczeństwa informacji · rozdz. 3, pkt 3.1", "ostatni przegląd: styczeń 2026"],
          ["„Każdy nowy pracownik przechodzi szkolenie wstępne z zasad bezpieczeństwa informacji.”", "Polityka bezpieczeństwa informacji · rozdz. 5, pkt 5.2", "brak zapisu o szkoleniach okresowych"],
          ["„Incydenty bezpieczeństwa zgłasza się do działu IT w terminie 7 dni od wykrycia.”", "Polityka bezpieczeństwa informacji · rozdz. 7, pkt 7.4", "NIS2 wymaga wczesnego ostrzeżenia w 24 h"],
          ["„Lista dostawców usług IT stanowi załącznik nr 2 do polityki.”", "Polityka bezpieczeństwa informacji · zał. 2", "lista bez oceny ryzyka dostawców"]
        ],
        pairs: [
          { req: "01 polityka bezpieczeństwa", ref: "NIS2 art. 21 ust. 2 lit. a", frag: 1, state: "ok", verdict: "spełnione" },
          { req: "02 zarządzanie ryzykiem", ref: "NIS2 art. 21 ust. 1", frag: 0, state: "ok", verdict: "spełnione" },
          { req: "03 obsługa incydentów", ref: "NIS2 art. 23: wczesne ostrzeżenie w 24 h", frag: 3, state: "gap", verdict: "niezgodność" },
          { req: "04 ciągłość działania", ref: "NIS2 art. 21 ust. 2 lit. c", frag: -1, state: "missing", verdict: "brak w dokumentacji" },
          { req: "05 szkolenia z cyberbezpieczeństwa", ref: "NIS2 art. 21 ust. 2 lit. g", frag: 2, state: "ok", verdict: "spełnione" },
          { req: "06 bezpieczeństwo łańcucha dostaw", ref: "NIS2 art. 21 ust. 2 lit. d", frag: 4, state: "gap", verdict: "wymaga uzupełnienia" }
        ] },
      { input: "Procedury wewnętrzne organizacji · gotowy zestaw wymagań: AI Act",
        checks: ["interpretacja wymagań AI Act", "analiza dokumentacji organizacji", "identyfikacja luk: obszar wymaga uzupełnienia"],
        target: "report",
        preview: "<b>Ocena poziomu zgodności: częściowa</b> · 2 z 3 wymagań<br>01 rejestr systemów AI - spełnione („procedura P-12, pkt 2” · AI Act art. 49)<br>02 nadzór człowieka - spełnione („P-12, pkt 5: decyzję zatwierdza pracownik” · AI Act art. 14)<br>03 dokumentacja techniczna - wymaga uzupełnienia (brak opisu danych treningowych i metryk · AI Act art. 11, załącznik IV)",
        rows: [["check", "01 rejestr systemów AI - spełnione", ""], ["check", "02 nadzór człowieka - spełnione", ""], ["flag", "03 dokumentacja techniczna - wymaga uzupełnienia", "gap"]],
        badge: "rekomendacje: objąć systemy AI procesem rejestrowania zdarzeń, uruchomić proces przygotowania i utrzymania dokumentacji technicznej",
        steps: ["wczytano dokumentację: Procedury wewnętrzne organizacji", "gotowy zestaw wymagań: AI Act", null, null, null, "raport: 4 wymagania spełnione, 1 do uzupełnienia, 1 brak w dokumentacji", "zaproponowane zmiany wspierają osiągnięcie zgodności z wymaganiami"],
        doc: "Procedury wewnętrzne organizacji", req: "zestaw wymagań: AI Act", met: 4, total: 6,
        frags: [
          ["„Każdy system AI wykorzystywany w organizacji wpisuje się do rejestru systemów AI.”", "Procedura P-12 · pkt 2", "rejestr prowadzi dział organizacyjny"],
          ["„Decyzję przygotowaną z udziałem systemu AI zatwierdza upoważniony pracownik.”", "Procedura P-12 · pkt 5", "zatwierdzenie odnotowane w systemie obiegu spraw"],
          ["„Użytkownik jest informowany, że w obsłudze sprawy wykorzystano system AI.”", "Procedura P-12 · pkt 7", "wzór informacji w załączniku do procedury"],
          ["„Rejestr zdarzeń systemów informatycznych przechowuje się przez 12 miesięcy.”", "Procedura P-08 · pkt 4", "rejestr nie obejmuje zdarzeń systemów AI"],
          ["„Przed wdrożeniem system AI podlega klasyfikacji ryzyka.”", "Procedura P-12 · pkt 3", "klasyfikacja wg kategorii z AI Act"]
        ],
        pairs: [
          { req: "01 rejestr systemów AI", ref: "AI Act art. 49", frag: 0, state: "ok", verdict: "spełnione" },
          { req: "02 klasyfikacja ryzyka", ref: "AI Act art. 6", frag: 4, state: "ok", verdict: "spełnione" },
          { req: "03 nadzór człowieka", ref: "AI Act art. 14", frag: 1, state: "ok", verdict: "spełnione" },
          { req: "04 przejrzystość wobec użytkownika", ref: "AI Act art. 13", frag: 2, state: "ok", verdict: "spełnione" },
          { req: "05 rejestrowanie zdarzeń", ref: "AI Act art. 12", frag: 3, state: "gap", verdict: "wymaga uzupełnienia" },
          { req: "06 dokumentacja techniczna", ref: "AI Act art. 11, załącznik IV", frag: -1, state: "missing", verdict: "brak w dokumentacji" }
        ] },
      { input: "Regulaminy i rejestry organizacji · własna lista kontrolna użytkownika",
        checks: ["interpretacja wymagań z listy kontrolnej", "analiza dokumentacji organizacji", "identyfikacja luk: 1 pozycja listy bez pokrycia"],
        target: "report",
        preview: "<b>Ocena poziomu zgodności: wysoka</b> · 2 z 3 pozycji<br>01 regulamin organizacyjny - spełnione („§ 4: zakres odpowiedzialności komórek” · lista, pkt 1)<br>02 rejestr upoważnień - spełnione („rejestr R-3, aktualizacja: 2026” · lista, pkt 2)<br>03 procedura obiegu dokumentów - do uzupełnienia (brak zapisu o obiegu dokumentów elektronicznych · lista, pkt 3)",
        rows: [["check", "01 regulamin organizacyjny - spełnione", ""], ["check", "02 rejestr upoważnień - spełnione", ""], ["flag", "03 procedura obiegu dokumentów - do uzupełnienia", "gap"]],
        badge: "rekomendacje: wdrożyć proces obiegu dokumentów elektronicznych, wprowadzić roczny plan szkoleń pracowników",
        steps: ["wczytano dokumentację: Regulaminy i rejestry organizacji", "własna lista kontrolna użytkownika", null, null, null, "raport: 4 pozycje listy spełnione, 1 do uzupełnienia, 1 brak w dokumentacji", "bieżąca weryfikacja zgodności z wewnętrznymi zasadami i procedurami"],
        doc: "Regulaminy i rejestry organizacji", req: "własna lista kontrolna użytkownika", met: 4, total: 6,
        frags: [
          ["„Zakres odpowiedzialności poszczególnych komórek organizacyjnych określa § 4 regulaminu.”", "Regulamin organizacyjny · § 4", "schemat organizacyjny w załączniku nr 1"],
          ["„Rejestr upoważnień do przetwarzania danych prowadzi się w formie elektronicznej.”", "Rejestr R-3 · aktualizacja: 2026", "ostatni wpis: luty 2026"],
          ["„Regulamin podlega przeglądowi nie rzadziej niż co 2 lata.”", "Regulamin organizacyjny · § 9", "ostatni przegląd: 2025"],
          ["„Umowy powierzenia przetwarzania danych ewidencjonuje się w rejestrze R-1.”", "Rejestr R-1 · umowy powierzenia", "12 umów, wszystkie aktualne"],
          ["„Obieg dokumentów papierowych odbywa się przez kancelarię ogólną.”", "Regulamin organizacyjny · § 12", "brak zasad dla dokumentów elektronicznych"]
        ],
        pairs: [
          { req: "01 regulamin organizacyjny", ref: "lista kontrolna, pkt 1", frag: 0, state: "ok", verdict: "spełnione" },
          { req: "02 rejestr upoważnień", ref: "lista kontrolna, pkt 2", frag: 1, state: "ok", verdict: "spełnione" },
          { req: "03 procedura obiegu dokumentów", ref: "lista kontrolna, pkt 3", frag: 4, state: "gap", verdict: "do uzupełnienia" },
          { req: "04 aktualność regulaminu", ref: "lista kontrolna, pkt 4", frag: 2, state: "ok", verdict: "spełnione" },
          { req: "05 umowy powierzenia danych", ref: "lista kontrolna, pkt 5", frag: 3, state: "ok", verdict: "spełnione" },
          { req: "06 plan szkoleń pracowników", ref: "lista kontrolna, pkt 6", frag: -1, state: "missing", verdict: "brak w dokumentacji" }
        ] },
    ]
  },
  {
    id: "klara", name: "Klara", tagline: "bezpieczny (i inteligentny) <em>chat AI</em>",
    tabs: ["dane poufne", "zadanie rutynowe", "zadanie złożone"],
    nodes: { input: { title: "Zapytanie pracownika", icon: "message-square-text" }, process: { title: "Analiza zapytania", icon: "scan-search", icons: ["shield", "gauge", "route"] } },
    outputs: { local: { title: "Model lokalny", icon: "server" }, external: { title: "Model zewnętrzny", icon: "cloud" } },
    viz: { outcomes: [
      { key: "local", title: "Model lokalny", sub: "w infrastrukturze organizacji", icon: "server" },
      { key: "apiq", title: "Quantica APIQ", sub: "modele hostowane przez Quantica", icon: "cloud" },
      { key: "frontier", title: "Frontier API", sub: "OpenAI · Anthropic · Gemini", icon: "globe" }
    ] },
    scenarios: [
      { input: "Przygotuj podsumowanie notatki zawierającej dane wynagrodzeń pracowników",
        checks: ["analiza bezpieczeństwa: wykryto dane wymagające ochrony", "analiza złożoności: zadanie standardowe", "decyzja: model lokalny - dane nie mogą opuścić organizacji"],
        target: "local",
        preview: "Jeżeli polecenie zawiera informacje wewnętrzne, poufne lub inne dane, które zgodnie z polityką organizacji nie powinny być przetwarzane poza jej infrastrukturą, zadanie jest realizowane przez lokalny model językowy działający w kontrolowanym środowisku.",
        rows: [["server", "koszt: bez opłat za API · dane: w organizacji · czas: krótki", ""], ["lock", "dane wymagające ochrony nie są przekazywane do zewnętrznych dostawców modeli AI", "gap"]],
        badge: "dane pozostają w infrastrukturze organizacji",
        steps: ["odebrano zapytanie pracownika", "analiza treści zapytania", null, null, null, "zadanie realizowane przez lokalny model językowy w kontrolowanym środowisku", "dane wymagające ochrony nie są przekazywane do zewnętrznych dostawców modeli AI"],
        route: { local: "on", apiq: "locked", frontier: "locked" }, checkRoutes: ["risk", "local", "local"] },
      { input: "Popraw styl krótkiej wiadomości do zespołu",
        checks: ["analiza bezpieczeństwa: brak danych wymagających ochrony", "analiza złożoności: zadanie proste i rutynowe", "decyzja: model lokalny - wystarczająca jakość przy niższym koszcie"],
        target: "local",
        preview: "Proste i rutynowe zadania są obsługiwane przez modele lokalne, co ogranicza koszty korzystania z zewnętrznych usług AI.",
        rows: [["server", "koszt: bez opłat za API · jakość: wystarczająca dla zadań rutynowych", ""]],
        badge: "efektywne wykorzystanie własnej infrastruktury",
        steps: ["odebrano zapytanie pracownika", "analiza treści zapytania", null, null, null, "zadanie skierowane do modelu lokalnego", "ograniczenie kosztów korzystania z zewnętrznych usług AI"],
        route: { local: "on", apiq: "off", frontier: "off" }, checkRoutes: ["any", "local", "local"] },
      { input: "Przygotuj pogłębioną analizę dokumentu strategii na podstawie danych publicznych",
        checks: ["analiza bezpieczeństwa: brak danych wymagających ochrony", "analiza złożoności: zadanie wymaga najbardziej zaawansowanego modelu", "decyzja: model zewnętrzny - Quantica APIQ lub frontier API"],
        target: "external",
        preview: "Zadania wymagające możliwości najbardziej zaawansowanych modeli są kierowane do wybranego modelu zewnętrznego, takiego jak GPT czy Gemini.",
        rows: [["cloud", "koszt: wg cennika Quantica APIQ lub dostawcy frontier API · na zewnątrz: tylko treść zadania", ""]],
        badge: "odpowiednia jakość odpowiedzi dla złożonego zadania",
        steps: ["odebrano zapytanie pracownika", "analiza treści zapytania", null, null, null, "zadanie skierowane do modelu zewnętrznego: Quantica APIQ lub frontier API", "model komercyjny wykorzystany tam, gdzie jego możliwości przynoszą rzeczywistą wartość"],
        route: { local: "off", apiq: "on", frontier: "alt" }, checkRoutes: ["any", "external", "external"] }
    ]
  },
  {
    id: "kmicic", name: "Kmicic", tagline: "inteligentny <em>agent e-mail</em>",
    tabs: ["zapytanie o procedurę", "sprawa dla eksperta", "zgłoszenie awarii"],
    nodes: { input: { title: "Wiadomość e-mail", icon: "inbox" }, process: { title: "Analiza wiadomości", icon: "scan-search", icons: ["file-text", "tag", "database"] } },
    outputs: { reply: { title: "Propozycja odpowiedzi", icon: "mail-check" }, route: { title: "Właściwa osoba lub zespół", icon: "users" }, ticket: { title: "Zgłoszenie w systemie", icon: "ticket" } },
    viz: { lanes: [
      { key: "reply", title: "Odpowiedź", sub: "propozycja do zatwierdzenia", icon: "mail-check" },
      { key: "route", title: "Przekazanie", sub: "właściwa osoba lub zespół", icon: "users" },
      { key: "ticket", title: "Zgłoszenie", sub: "ticket w systemie obsługi spraw", icon: "ticket" }
    ] },
    scenarios: [
      { input: "Proszę o informację, jakie dokumenty należy dołączyć do wniosku - w załączniku przesyłam skan pisma",
        checks: ["analiza treści: zidentyfikowano temat i zakres sprawy", "klasyfikacja: zapytanie o procedurę, priorytet standardowy", "wyszukiwanie w bazie wiedzy organizacji: znaleziono informacje, wskazano źródła"],
        target: "reply",
        preview: "Dzień dobry, do wniosku należy dołączyć: 1) wypełniony formularz, 2) potwierdzenie wniesienia opłaty, 3) pełnomocnictwo, jeśli wniosek składa pełnomocnik. Pełna lista: karta usługi <span class=\"ref\">[1]</span>. <span class=\"more\">(…)</span>",
        rows: [["file-text", "[1] Karta usługi: złożenie wniosku.pdf", ""], ["file-text", "[2] Instrukcja dla wnioskodawców.docx", ""]],
        badge: "czeka na zatwierdzenie przez pracownika (human-in-the-loop)",
        chips: [["temat", "zapytanie o procedurę"], ["priorytet", "standardowy"], ["załącznik", "skan pisma"], ["baza wiedzy", "znaleziono 2 źródła"]], sender: "mieszkaniec", subject: "Dokumenty do wniosku", attach: "skan_pisma.pdf",
        mailBody: ["Dzień dobry,", "w ubiegłym tygodniu otrzymałem pismo w sprawie mojego wniosku (skan w załączniku). Proszę o informację, jakie dokumenty należy dołączyć do wniosku i czy mogę je przesłać elektronicznie.", "Czy potrzebne jest również potwierdzenie wniesienia opłaty? Będę wdzięczny za odpowiedź w tym tygodniu."],
        sign: ["Z poważaniem", "Jan K.", "mieszkaniec · tel. …"], approved: "zatwierdzono i wysłano - pracownik zmienił jedno zdanie",
        steps: ["odebrano wiadomość e-mail wraz z załącznikiem", "analiza treści wiadomości i załącznika", null, null, null, "dostępne informacje pozwalają na obsługę sprawy - przygotowano propozycję odpowiedzi", "propozycja odpowiedzi czeka na zatwierdzenie przez pracownika (human-in-the-loop)"] },
      { input: "Proszę o indywidualną interpretację zapisów umowy w nietypowej sprawie",
        checks: ["analiza treści: zidentyfikowano temat i zakres sprawy", "klasyfikacja: sprawa wymaga indywidualnej decyzji, priorytet podwyższony", "wyszukiwanie w bazie wiedzy organizacji: sprawa wymaga wiedzy eksperckiej"],
        target: "route",
        preview: "<b>Do: radca prawny.</b> Sprawa: interpretacja § 7 umowy w sytuacji nieopisanej w umowie.<br>Kontekst: wiadomość, umowa <span class=\"ref\">[1]</span>, wcześniejsza korespondencja <span class=\"ref\">[2]</span>.<br>Rekomendacja: odpowiedź indywidualna, termin wg procedury.",
        rows: [["file-text", "[1] Umowa nr …/2025 (§ 7)", ""], ["mails", "[2] wcześniejsza korespondencja w sprawie: 3 wiadomości", ""]],
        badge: "pełny kontekst i rekomendacja działań",
        chips: [["temat", "sprawa indywidualna: interpretacja umowy"], ["priorytet", "podwyższony"], ["decyzja", "wymaga wiedzy eksperckiej"], ["kontekst", "umowa + 3 wcześniejsze wiadomości"]], sender: "kontrahent", subject: "Interpretacja § 7 umowy nr …/2025", attach: "",
        mailBody: ["Szanowni Państwo,", "w związku z realizacją umowy nr …/2025 pojawiła się sytuacja, której § 7 wprost nie opisuje: część prac musi zostać wykonana poza pierwotnym harmonogramem z przyczyn niezależnych od stron.", "Proszę o indywidualną interpretację zapisów umowy w tej nietypowej sprawie oraz o wskazanie, w jakim trybie możemy uzgodnić zmianę terminu. Nawiązuję do naszej wcześniejszej korespondencji z marca."],
        sign: ["Z wyrazami szacunku", "Anna W.", "kierownik projektu · kontrahent"],
        steps: ["odebrano wiadomość e-mail", "analiza treści wiadomości", null, null, null, "zidentyfikowano właściwą ścieżkę obsługi - sprawa przekazana do właściwej osoby", "przygotowano podsumowanie sprawy, pełny kontekst i rekomendację dalszych działań"] },
      { input: "Zgłaszam awarię systemu rezerwacji - proszę o pilną obsługę",
        checks: ["analiza treści: zidentyfikowano temat i zakres sprawy", "klasyfikacja: zgłoszenie techniczne, priorytet wysoki", "wyszukiwanie w bazie wiedzy organizacji: procedura obsługi zgłoszeń"],
        target: "ticket",
        preview: "<b>Zgłoszenie #…</b> · kategoria: awaria systemu · priorytet: wysoki<br>właściciel: zespół IT · termin reakcji: wg procedury <span class=\"ref\">[1]</span><br>zgłaszający powiadomiony o numerze sprawy",
        rows: [["file-text", "[1] Procedura obsługi zgłoszeń IT.pdf", ""]],
        badge: "właściciel przypisany, terminy monitorowane",
        chips: [["temat", "zgłoszenie techniczne"], ["priorytet", "wysoki"], ["kategoria", "awaria systemu rezerwacji"], ["baza wiedzy", "procedura obsługi zgłoszeń IT"]], sender: "pracownik", subject: "PILNE: awaria systemu rezerwacji", attach: "",
        mailBody: ["Dzień dobry,", "od godziny 8:15 system rezerwacji nie przyjmuje nowych zgłoszeń, a przy próbie zapisu pojawia się komunikat o błędzie serwera. Dotyczy to wszystkich stanowisk w biurze obsługi.", "Zgłaszam awarię systemu rezerwacji i proszę o pilną obsługę. W razie potrzeby jestem dostępny pod numerem wewnętrznym."],
        sign: ["Pozdrawiam", "Marek N.", "biuro obsługi · wew. …"],
        steps: ["odebrano wiadomość e-mail", "analiza treści wiadomości", null, null, null, "utworzono zgłoszenie (ticket) w systemie obsługi spraw", "uzupełniono metadane, kategorię i priorytet - przypisano właściciela zgłoszenia"] }
    ]
  },
  {
    id: "ocena", name: "Ocena modeli", tagline: "porównanie <em>modeli i systemów AI</em>",
    tabs: ["klasyfikacja", "wydobycie informacji", "streszczanie"],
    nodes: { input: { title: "Zestaw zadań", icon: "files" }, process: { title: "Ocena wg jednolitych kryteriów", icon: "scan-search", icons: ["target", "badge-check", "languages"] } },
    outputs: { result: { title: "Porównanie wyników", icon: "bar-chart-3" } },
    viz: { models: [["A", "Model A", "lokalny, open-source"], ["B", "Model B", "komercyjny"], ["C", "Model C", "komercyjny"]], criteria: ["zgodność z zadaniem", "poprawność informacji", "jakość języka polskiego"] },
    scenarios: [
      { input: "Przypisz każde ze 120 pism przychodzących do właściwej kategorii spraw",
        checks: ["kryterium 1/3: zgodność z zadaniem - ocenione dla wszystkich modeli", "kryterium 2/3: poprawność informacji - ocenione dla wszystkich modeli", "kryterium 3/3: jakość języka polskiego - ocenione dla wszystkich modeli"],
        target: "result",
        preview: "<b>Wynik łączny</b> (średnia z trzech kryteriów)<br>Model A: 94/100 · Model B: 93/100 · Model C: 91/100<br>Wyniki zbliżone - zadanie może skutecznie realizować model lokalny, bez kosztownego dostrajania.",
        rows: [["award", "Model A · 94/100", ""], ["bar-chart-3", "Model B · 93/100", "gap"], ["bar-chart-3", "Model C · 91/100", "gap"]],
        badge: "najwyższa skuteczność w tym zadaniu: Model A",
        steps: ["przygotowano zestaw zadań: klasyfikacja dokumentów", "odpowiedzi wszystkich modeli oceniane wg jednolitych kryteriów", null, null, null, "wynik łączny: średnia z trzech kryteriów dla każdego modelu", "wyniki zbliżone - zadanie może skutecznie realizować model lokalny, bez kosztownego dostrajania"],
        scores: { A: [95, 94, 93], B: [94, 93, 92], C: [92, 91, 90] }, best: "A",
        samplesLabel: "przykładowe zadania z zestawu (120 pism)",
        samples: [["„Proszę o wydanie zaświadczenia o zameldowaniu…”", "sprawy meldunkowe"], ["„Zgłaszam uszkodzenie nawierzchni na ul. …”", "infrastruktura"], ["„Wniosek o udostępnienie informacji publicznej…”", "informacja publiczna"]] },
      { input: "Wskaż strony umowy, terminy realizacji oraz kwoty we wskazanych dokumentach",
        checks: ["kryterium 1/3: zgodność z zadaniem - ocenione dla wszystkich modeli", "kryterium 2/3: poprawność informacji - ocenione dla wszystkich modeli", "kryterium 3/3: jakość języka polskiego - ocenione dla wszystkich modeli"],
        target: "result",
        preview: "<b>Wynik łączny</b> (średnia z trzech kryteriów)<br>Model A: 78/100 · Model B: 93/100 · Model C: 88/100<br>Wyraźna przewaga modelu B (zwłaszcza poprawność) - w tym zadaniu warto wykorzystać model komercyjny.",
        rows: [["award", "Model B · 93/100", ""], ["bar-chart-3", "Model C · 88/100", "gap"], ["bar-chart-3", "Model A · 78/100", "gap"]],
        badge: "najwyższa skuteczność w tym zadaniu: Model B",
        steps: ["przygotowano zestaw zadań: wydobycie informacji", "odpowiedzi wszystkich modeli oceniane wg jednolitych kryteriów", null, null, null, "wynik łączny: średnia z trzech kryteriów dla każdego modelu", "wyraźna przewaga modelu B (zwłaszcza poprawność) - w tym zadaniu warto wykorzystać model komercyjny"],
        scores: { A: [82, 71, 81], B: [94, 93, 92], C: [89, 87, 88] }, best: "B",
        samplesLabel: "przykładowe zadania z zestawu (dokumenty umów)",
        samples: [["Umowa nr 12/2025 · strony: Gmina …, Firma …", "strony umowy"], ["„…wykonawca zakończy prace do 30 czerwca 2026 r.”", "termin realizacji"], ["„…wynagrodzenie w kwocie 48 000 zł netto”", "kwota"]] },
      { input: "Przygotuj streszczenie 40-stronicowego raportu na potrzeby zarządu",
        checks: ["kryterium 1/3: zgodność z zadaniem - ocenione dla wszystkich modeli", "kryterium 2/3: poprawność informacji - ocenione dla wszystkich modeli", "kryterium 3/3: jakość języka polskiego - ocenione dla wszystkich modeli"],
        target: "result",
        preview: "<b>Wynik łączny</b> (średnia z trzech kryteriów)<br>Model A: 72/100 · Model B: 89/100 · Model C: 92/100<br>Model lokalny traci głównie na poprawności informacji - douczenie może znacząco poprawić jego skuteczność.",
        rows: [["award", "Model C · 92/100", ""], ["bar-chart-3", "Model B · 89/100", "gap"], ["bar-chart-3", "Model A · 72/100", "gap"]],
        badge: "najwyższa skuteczność: Model C - obszar do douczenia modelu lokalnego",
        steps: ["przygotowano zestaw zadań: streszczanie dokumentów", "odpowiedzi wszystkich modeli oceniane wg jednolitych kryteriów", null, null, null, "wynik łączny: średnia z trzech kryteriów dla każdego modelu", "model lokalny traci głównie na poprawności informacji - douczenie może znacząco poprawić jego skuteczność"],
        scores: { A: [76, 66, 74], B: [90, 88, 89], C: [93, 91, 92] }, best: "C",
        samplesLabel: "przykładowe zadania z zestawu (raporty 20-60 stron)",
        samples: [["Raport roczny działu IT, 40 stron", "streszczenie na 1 stronę"], ["Sprawozdanie z audytu wewnętrznego, 28 stron", "5 kluczowych wniosków"], ["Analiza ryzyka projektu, 55 stron", "podsumowanie dla zarządu"]] }
    ]
  },
  {
    id: "papkin", name: "Papkin", tagline: "inteligentny <em>protokolant AI</em>",
    tabs: ["spotkanie na żywo", "nagranie audio", "spotkanie dwujęzyczne"],
    nodes: { input: { title: "Dźwięk ze spotkania", icon: "audio-lines" }, process: { title: "Transkrypcja i analiza", icon: "mic", icons: ["audio-waveform", "users", "spell-check"] } },
    outputs: { docs: { title: "Dokumentacja spotkania", icon: "file-text" } },
    scenarios: [
      { input: "Ustalamy termin wdrożenia na koniec kwartału. Zespół projektowy przygotuje harmonogram prac.",
        checks: ["rozpoznawanie mowy (ASR) uruchomione lokalnie", "rozróżniono mówców - wypowiedzi oznaczone według uczestników", "poprawa jakości transkrypcji i porządkowanie wypowiedzi"],
        target: "docs",
        preview: "<span class=\"spk\">Mówca 1</span> Ustalamy termin wdrożenia na koniec kwartału.<br><span class=\"spk\">Mówca 2</span> Zespół projektowy przygotuje harmonogram prac.<br><b>zadanie:</b> harmonogram prac · <b>odpowiada:</b> zespół projektowy · <b>termin:</b> koniec kwartału",
        rows: [["file-check", "protokół spotkania", ""], ["file-check", "zestawienie ustaleń", ""], ["file-check", "lista zadań", ""]],
        badge: "materiały przesłane uczestnikom spotkania",
        steps: ["odebrano dźwięk ze spotkania - transkrypcja w czasie rzeczywistym", "przetwarzanie lokalne w infrastrukturze organizacji", null, null, null, "zidentyfikowano kluczowe ustalenia, decyzje i zadania", "opracowane materiały przesłane uczestnikom spotkania"],
        segments: [["Mówca 1", 46], ["Mówca 2", 54]],
        lines: [["Mówca 1", "Ustalamy termin wdrożenia na koniec kwartału."], ["Mówca 2", "Zespół projektowy przygotuje harmonogram prac."]],
        task: "<b>zadanie:</b> harmonogram prac · <b>odpowiada:</b> zespół projektowy · <b>termin:</b> koniec kwartału", live: true },
      { input: "Przyjmujemy wariant drugi budżetu. Notatkę służbową przygotuje dział organizacyjny.",
        checks: ["transkrypcja nagrania audio - przetwarzanie lokalne", "profile głosowe - zidentyfikowano konkretne osoby", "korekta błędów rozpoznawania mowy i ujednolicenie zapisu"],
        target: "docs",
        preview: "<span class=\"spk\">A. Nowak</span> Przyjmujemy wariant drugi budżetu.<br><span class=\"spk\">M. Wiśniewska</span> Notatkę służbową przygotuje dział organizacyjny.<br><b>decyzja:</b> wariant 2 budżetu · <b>zadanie:</b> notatka służbowa · <b>odpowiada:</b> dział organizacyjny",
        rows: [["file-check", "notatka służbowa", ""], ["file-check", "podsumowanie kierownicze", ""], ["file-check", "lista zadań", ""]],
        badge: "podsumowanie przekazane kierownictwu",
        steps: ["wczytano wcześniej przygotowane nagranie audio", "przetwarzanie lokalne w infrastrukturze organizacji", null, null, null, "zidentyfikowano kluczowe ustalenia i decyzje", "podsumowanie przekazane wskazanym osobom i kierownictwu"],
        segments: [["A. Nowak", 40], ["M. Wiśniewska", 60]],
        lines: [["A. Nowak", "Przyjmujemy wariant drugi budżetu."], ["M. Wiśniewska", "Notatkę służbową przygotuje dział organizacyjny."]],
        task: "<b>decyzja:</b> wariant 2 budżetu · <b>zadanie:</b> notatka służbowa · <b>odpowiada:</b> dział organizacyjny", live: false },
      { input: "Let's confirm the scope for phase two. Zespół po stronie polskiej przygotuje specyfikację.",
        checks: ["rozpoznawanie mowy (ASR) dla wypowiedzi w obu językach", "rozróżniono mówców - wypowiedzi oznaczone według uczestników", "tłumaczenie treści pomiędzy językiem polskim i angielskim"],
        target: "docs",
        preview: "<span class=\"spk\">Speaker 1 · EN</span> Let's confirm the scope for phase two. <span class=\"tr\">PL: Potwierdźmy zakres drugiego etapu.</span><span class=\"spk\">Mówca 2 · PL</span> Zespół po stronie polskiej przygotuje specyfikację. <span class=\"tr\">EN: The Polish team will prepare the specification.</span>",
        rows: [["file-check", "protokół spotkania (PL i EN)", ""], ["file-check", "zestawienie ustaleń", ""], ["file-check", "lista zadań", ""]],
        badge: "materiały przesłane uczestnikom spotkania",
        steps: ["odebrano dźwięk - wypowiedzi w języku polskim i angielskim", "przetwarzanie lokalne w infrastrukturze organizacji", null, null, null, "zidentyfikowano kluczowe ustalenia, decyzje i zadania", "opracowane materiały przesłane uczestnikom spotkania"],
        segments: [["Speaker 1 · EN", 48], ["Mówca 2 · PL", 52]],
        lines: [["Speaker 1 · EN", "Let's confirm the scope for phase two.", "PL: Potwierdźmy zakres drugiego etapu."], ["Mówca 2 · PL", "Zespół po stronie polskiej przygotuje specyfikację.", "EN: The Polish team will prepare the specification."]],
        task: "<b>task:</b> specification for phase two · <b>owner:</b> Polish team · <b>zadanie:</b> specyfikacja etapu 2", live: true }
    ]
  }
];